### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by jfoxx** [jcfabbri/TestEdgeSite#4]
Cards have just an image and a headline and link to another page. Block on doc will need to collect each item separately:

| Card |
|--------|--------|--------|
| Image | Title | URL |

![image](https://github.com/jcfabbri/TestEdgeSite/assets/88052587/6d915326-1beb-4894-98cd-e0a471888ef8)

**Comment by jcfabbri** [comment]
Will create a new feature card naming here to provide hover capabilities and not conflict w landing page cards
